### PR TITLE
feat(post): add copy code to clipboard button (#339)

### PR DESCRIPTION
**Pull request by Chasing1020**

### CODE REVIEW

**Comment by lucumt** [comment]
Is there a way to disable copy code function if we browser via mobile phone? Seems it doesn't work in mobile phone

**Comment by Chasing1020** [comment]
@lucumt I tried your code by using the "toggle device toolbar" to simulate mobile devices in Chrome(ver 105.0.5195.102) and it works well. So have you tried to check the value of `navigator.userAgent` on your Mobile? If still not, you can use `window.innerWidth < window.innerHeight` instead.

**Comment by lucumt** [comment]
@Chasing1020 I have tried `navigator.userAgent` in myside, and it works fine in my website(https://lucumt.info),I am wondering if there are more elegant way to do it

**Comment by Chasing1020** [comment]
It seems js doesn't have the built-in method to distinguish the device, and regex works well.

**Comment by lucumt** [comment]
@Chasing1020 This theme has a **back-to-top** button appear in the right down side of web page when the page has large height ,but I have tested in my mobile phone browser and found the button not appeared in mobile browser,this might be for your information.

**Comment by Chasing1020** [comment]
@lucumt 
The `back-to-top` button uses the @media method to detect the screen size. And you can add these lines in the `./themes/even/assets/sass/_partial/_post/_code.scss` file. Hope it could help you.
```scss
@include max-screen() {
  .copy-code {
    display: none !important;
  }
}
```

**Pull request closed without merging**
