### PR TITLE
Katex, all-site math support and currently sexiest mermaid support (?)

### PR DESCRIPTION
**Pull request by ClSlaid**
Signed-off-by: ClSlaid <cailue@bupt.edu.cn>

I know few about front end but I managed to add `katex` support for your theme.
And as an answer to issue #333, it is not a mathjax problem but a template problem. By changing `mathAllSections` in `config.toml` to true enables math rendering on all pages. as for performance concern it's false by default.

The determine statements in template are too long and I don't know how to warp them into multiple lines.
[mathjax determine statement](https://github.com/ClSlaid/hugo-theme-even/blob/a32b7c49a862ce58a859f0964bf5b588df638339/layouts/partials/scripts.html#L76)
[katex determine statement](https://github.com/ClSlaid/hugo-theme-even/blob/a32b7c49a862ce58a859f0964bf5b588df638339/layouts/partials/scripts.html#L97)

### CODE REVIEW

**Comment by ClSlaid** [comment]
I'm glad to say after a day of configuration I managed to add mermaid support for the theme. Now you can use mermaid like `flowcharts` and `sequence diagrams`.

example:

\```mermaid
graph LR
A(面试)-->B(笔试)
A-->C(面试)
C-->C1(数据结构与算法*)
C-->C2(计算机网络)
C-->C3(操作系统Linux)
B-->B1(数据结构与算法*)
\```

image

It feels much better than {{<mermaid>}} I think, my typora editor will surely feel happy about it.

**Comment by ClSlaid** [comment]
Now you can change mermaid style by configuring `config.toml`.
image
image

**Comment by ClSlaid** [comment]
@olOwOlo Please take a look and merge it...

**Comment by ClSlaid** [comment]
@olOwOlo PTAL.

**Comment by daniel-hutao** [comment]
+1

**Comment by ClSlaid** [comment]
@olOwOlo Please take a look.

**Pull request closed without merging**
