### PR TITLE
讓MathJax支援單$即可渲染

### PR DESCRIPTION
**Pull request by henrybear327**
[官方文件](https://docs.mathjax.org/en/latest/start.html#tex-and-latex-input)提及的方法！

### CODE REVIEW

**Comment by olOwOlo** [comment]
> That is because dollar signs appear too often in non-mathematical settings, which could cause some text to be treated as mathematics unexpectedly. For example, with single-dollar delimiters, ”... the cost is $2.50 for the first one, and $2.00 for each additional one ...” would cause the phrase “2.50 for the first one, and” to be treated as mathematics since it falls between dollar signs.

文档里也说了为什么 `$...$` 默认不开启，我认为还是让有需求的同学自行添加比较好~

**Comment by henrybear327** [comment]
還是我開成參數呢? 感覺以後要加的話也方便些!

**Comment by olOwOlo** [comment]
额，幸苦~
设置成参数可以的，麻烦统一下设置方式和缩进~
还有不要移动 Google Analytics，，，在某些地区使用不支持异步加载的浏览器请求 Google 的资源是会长时间阻塞页面渲染的，，，

**Comment by henrybear327** [comment]
好的，我來研究一下並提交修改

移動Google Analytics是我自己實驗性質的code
抱歉我沒注意到他會被同步過來
我會拿掉

**Comment by henrybear327** [comment]
我另外開一個PR吧！

**Comment by olOwOlo** [comment]
可以设置 `google_verification` 这个参数输出
```html
<meta name="google-site-verification" content="设置的字符串">
```
来验证的~

**Comment by henrybear327** [comment]
謝謝提點，太菜了沒注意到這個 :'(

**Pull request closed without merging**
